apiVersion: 1
contactPoints:
  - name: EmailAlerts
    receivers:
      - type: email
        settings:
          addresses: ukrainskyi.vitalii@gmail.com
groups:
  - name: ResourceAlerts
    interval: 5m
    folder: Alerts
    rules:
      - title: High CPU Usage Alert
        condition: C
        data:
          - refId: A
            model:
              expr: sum(rate(node_cpu_seconds_total{mode!="idle"}[5m])) by (instance) / sum(rate(node_cpu_seconds_total[5m])) by (instance) * 100
              interval: 5m
          - refId: B
            model:
              expr: A > 80
        annotations:
          summary: "CPU usage exceeded 80% on {{ $labels.instance }}"
        for: 1m
        noDataState: NoData
        execErrState: Error
        notification_settings:
          receiver: EmailAlerts

      - title: High Memory Usage Alert
        condition: C
        data:
          - refId: A
            model:
              expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100
              interval: 5m
          - refId: B
            model:
              expr: A > 80
        annotations:
          summary: "Memory usage exceeded 80% on {{ $labels.instance }}"
        for: 1m
        noDataState: NoData
        execErrState: Error
        notification_settings:
          receiver: EmailAlerts
