apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alerts
  namespace: jenkins
data:
  contact-point.json: |
    {
      "name": "email-alert",
      "type": "email",
      "settings": {
        "addresses": "alerts@example.com",
        "subject": "Grafana Alert",
        "textBody": "Alert: {{ .Labels.alertname }} triggered on {{ .Labels.instance }}."
      }
    }
  cpu-alert.json: |
    {
      "dashboardUid": "cpu-alert-dashboard",
      "panelId": 1,
      "name": "High CPU Usage",
      "type": "alert",
      "conditions": [
        {
          "evaluator": { "type": "gt", "params": [80] },
          "operator": { "type": "and" },
          "query": { "params": ["A", "5m", "now"] },
          "reducer": { "type": "avg" },
          "type": "query"
        }
      ],
      "executionErrorState": "alerting",
      "frequency": "60s",
      "for": "5m",
      "handler": 1,
      "message": "CPU usage is above 80%",
      "noDataState": "no_data",
      "notifications": [
        {
          "uid": "email-alert"
        }
      ]
    }
