apiVersion: v1
data:
  prometheus.yaml: |
    global:
      external_labels:
        monitor: prometheus
    scrape_configs:
      - job_name: node-exporter
        scrape_interval: 1m
        metrics_path: /metrics
        static_configs:
          - targets:
            - node-exporter.jenkins.svc.cluster.local:9100
      - job_name: kube-state-metrics
        scrape_interval: 1m
        metrics_path: /metrics
        static_configs:
          - targets:
            - kube-state-metrics.jenkins.svc.cluster.local:8080
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            target_label: __address__
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
      - job_name: prometheus
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
              - jenkins
        metrics_path: /metrics
        relabel_configs:
          - source_labels:
              - job
            target_label: __tmp_prometheus_job_name
          - action: keep
            source_labels:
              - __meta_kubernetes_service_label_app_kubernetes_io_component
              - __meta_kubernetes_service_labelpresent_app_kubernetes_io_component
            regex: (server);true
          - action: keep
            source_labels:
              - __meta_kubernetes_service_label_app_kubernetes_io_instance
              - __meta_kubernetes_service_labelpresent_app_kubernetes_io_instance
            regex: (prometheus);true
          - action: keep
            source_labels:
              - __meta_kubernetes_service_label_app_kubernetes_io_name
              - __meta_kubernetes_service_labelpresent_app_kubernetes_io_name
            regex: (prometheus);true
          - action: keep
            source_labels:
              - __meta_kubernetes_endpoint_port_name
            regex: http
          - source_labels:
              - __meta_kubernetes_endpoint_address_target_kind
              - __meta_kubernetes_endpoint_address_target_name
            separator: ;
            regex: Node;(.*)
            replacement: ${1}
            target_label: node
          - source_labels:
              - __meta_kubernetes_endpoint_address_target_kind
              - __meta_kubernetes_endpoint_address_target_name
            separator: ;
            regex: Pod;(.*)
            replacement: ${1}
            target_label: pod
          - source_labels:
              - __meta_kubernetes_namespace
            target_label: namespace
          - source_labels:
              - __meta_kubernetes_service_name
            target_label: service
          - source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
          - source_labels:
              - __meta_kubernetes_pod_container_name
            target_label: container
          - action: drop
            source_labels:
              - __meta_kubernetes_pod_phase
            regex: (Failed|Succeeded)
          - source_labels:
              - __meta_kubernetes_service_name
            target_label: job
            replacement: ${1}
          - target_label: endpoint
            replacement: http
          - source_labels:
              - __address__
            target_label: __tmp_hash
            modulus: 1
            action: hashmod
          - source_labels:
              - __tmp_hash
            regex: 0
            action: keep
      - job_name: alertmanager
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
              - jenkins
        metrics_path: /metrics
        relabel_configs:
          - source_labels:
              - job
            target_label: __tmp_prometheus_job_name
          - action: keep
            source_labels:
              - __meta_kubernetes_service_label_app_kubernetes_io_component
              - __meta_kubernetes_service_labelpresent_app_kubernetes_io_component
            regex: (alertmanager);true
          - action: keep
            source_labels:
              - __meta_kubernetes_service_label_app_kubernetes_io_instance
              - __meta_kubernetes_service_labelpresent_app_kubernetes_io_instance
            regex: (prometheus);true
          - action: keep
            source_labels:
              - __meta_kubernetes_service_label_app_kubernetes_io_name
              - __meta_kubernetes_service_labelpresent_app_kubernetes_io_name
            regex: (prometheus);true
          - action: keep
            source_labels:
              - __meta_kubernetes_endpoint_port_name
            regex: http
          - source_labels:
              - __meta_kubernetes_endpoint_address_target_kind
              - __meta_kubernetes_endpoint_address_target_name
            separator: ;
            regex: Node;(.*)
            replacement: ${1}
            target_label: node
          - source_labels:
              - __meta_kubernetes_endpoint_address_target_kind
              - __meta_kubernetes_endpoint_address_target_name
            separator: ;
            regex: Pod;(.*)
            replacement: ${1}
            target_label: pod
          - source_labels:
              - __meta_kubernetes_namespace
            target_label: namespace
          - source_labels:
              - __meta_kubernetes_service_name
            target_label: service
          - source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
          - source_labels:
              - __meta_kubernetes_pod_container_name
            target_label: container
          - action: drop
            source_labels:
              - __meta_kubernetes_pod_phase
            regex: (Failed|Succeeded)
          - source_labels:
              - __meta_kubernetes_service_name
            target_label: job
            replacement: ${1}
          - target_label: endpoint
            replacement: http
          - source_labels:
              - __address__
            target_label: __tmp_hash
            modulus: 1
            action: hashmod
          - source_labels:
              - __tmp_hash
            regex: 0
            action: keep
    alerting:
      alertmanagers:
        - scheme: HTTP
          static_configs:
            - targets: [ "prometheus-alertmanager.jenkins.svc.cluster.local:80" ]
    rule_files:
      - rules.yaml
  rules.yaml: '{}'
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: jenkins
  creationTimestamp: "2024-11-30T13:47:04Z"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: prometheus
    app.kubernetes.io/version: 2.55.1
    helm.sh/chart: prometheus-1.3.28
  name: prometheus-server
  namespace: jenkins
  resourceVersion: "857"
  uid: 5bedc48b-aecf-4e49-ac52-78c2640052c8
